[package]
name = "gpu-usage-waybar"
authors = ["cymenix"]
version = "0.1.2"
edition = "2021"
description = "A tool to display gpu usage in Waybar"
license = "MIT"
readme = "README.md"
repository = "https://github.com/cymenix/gpu-usage-waybar"

[dependencies]
amdgpu-sysfs = "0.14.0"
color-eyre = "0.6.3"
lazy_static = "1.4.0"
nvml-wrapper = "0.10.0"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
strum = { version = "0.26.2", features = ["derive"] }

[profile.dev.package.backtrace]
opt-level = 3

# Rust does not inline across crates if link-time optimization (LTO) is off, which it is by default.
[profile.release]
lto = true
